### ISSUE TITLE
Issues with theming

### ISSUE THREAD

**Issue by Catnatsuki** [neatnik/omg.lol#174] opened 2021-11-29 08:53 UTC
When a custom CSS file is added after the theme 'hacker' was applied the font and colours in the custom CSS are ignored and the one from the hacker theme are used. 
Workaround: After the custom CSS file pasted and saved, apply the default theme.
![image](https://user-images.githubusercontent.com/52190402/143836792-5f6de4ea-7f31-466d-b464-cb93179c5988.png)

**Comment by newbold** [comment] 2021-11-29 13:25
Thanks for mentioning this. This will be addressed in the upcoming overhaul, where profile theming will be completely re-done!

**Comment by Catnatsuki** [comment] 2021-11-29 13:36
:0 nice! can't wait for the overhaul.

**Comment by newbold** [comment] 2022-08-15 17:31
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605846989018

**Comment by newbold** [comment] 2022-11-21 00:07
I believe this has been addressed in the theming overhaul, but there will be some further adjustments to themes to make things even more straightforward at some point. Until then, any situations like these might need some extra declarations and/or `!important`s to get things behaving as intended.

**Closed by newbold** 2022-11-21 00:07 UTC
Labels: enhancement, web/profiles
